# Generated by Django 5.1.8 on 2025-04-23 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcollection',
            name='created_at',
        ),
    ]
