# Generated by Django 5.1.8 on 2025-04-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_remove_productcollection_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=1, upload_to='Products/images', verbose_name='Resim'),
            preserve_default=False,
        ),
    ]
