# Generated by Django 5.1.8 on 2025-04-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcollection',
            name='image',
            field=models.ImageField(default='default.png', upload_to='Products/images', verbose_name='Resim'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default.png', upload_to='Products/images', verbose_name='Resim'),
        ),
    ]
